name: alchilazo
on: [push, pull_request]
jobs:
  drive:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: |
           flutter config --enable-windows-desktop
           flutter test -d windows test/mongo_test.dart
           flutter drive --target=test_driver/app.dart
